version: '3'

services:
  jekyll:
    container_name: faq-pages_github
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    volumes:
      - .:/srv/jekyll
    ports:
      - '4000:4000'